# Generated by Django 4.0.4 on 2022-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.TimeField(),
        ),
    ]
