# Generated by Django 4.0.4 on 2022-05-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_band_options_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music.album'),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='score',
            field=models.CharField(help_text='Format 1/10', max_length=5),
        ),
    ]
