# Generated by Django 4.0.4 on 2022-05-23 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_albumreview_album_id_alter_albumreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='music.album', verbose_name='Album'),
        ),
    ]
